from sqlalchemy import Column, Integer, BigInteger, String, DateTime, Numeric, ForeignKey, TIMESTAMP, JSON, Text
from sqlalchemy.sql import func
from database import Base


class DimCountry(Base):
    __tablename__ = "dim_country"
    id = Column(Integer, primary_key=True, autoincrement=True)
    code = Column(String(5), unique=True, nullable=False)
    name = Column("name", String(50), nullable=False)
    currency = Column(String(5), nullable=False)


class DimExchangeRate(Base):
    __tablename__ = "dim_exchange_rate"
    id = Column(Integer, primary_key=True, autoincrement=True)
    country_id = Column(Integer, ForeignKey("dim_country.id"), nullable=False)
    year_month = Column("year_month", String(7), nullable=False)
    rate = Column(Numeric(10, 4), nullable=False)


class DimStore(Base):
    __tablename__ = "dim_store"
    id = Column(Integer, primary_key=True, autoincrement=True)
    code = Column(String(50), unique=True, nullable=False)
    name = Column("name", String(100), nullable=False)
    created_at = Column(TIMESTAMP, server_default=func.now())


class DimProduct(Base):
    __tablename__ = "dim_product"
    id = Column(Integer, primary_key=True, autoincrement=True)
    asin = Column(String(50), unique=True, nullable=False)
    sku = Column(String(100))
    product_name = Column(String(500))
    color = Column(String(50))

class DimProductCost(Base):
    __tablename__ = "dim_product_cost"
    id = Column(Integer, primary_key=True, autoincrement=True)
    product_id = Column(Integer, ForeignKey("dim_product.id"), nullable=False)
    year_month = Column("ym", String(7), nullable=False)  # '2026-05'
    cost_rmb = Column(Numeric(10, 2), default=0)
    freight_per_unit = Column(Numeric(10, 2), default=0)
    exchange_rate = Column(Numeric(10, 4), nullable=True)


class DimTime(Base):
    __tablename__ = "dim_time"
    id = Column(Integer, primary_key=True, autoincrement=True)
    time_year = Column(Integer, nullable=False)
    time_month = Column(Integer, nullable=False)
    year_month = Column(String(7), unique=True, nullable=False)


class RawTransaction(Base):
    __tablename__ = "raw_transactions"
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    country_id = Column(Integer, ForeignKey("dim_country.id"), nullable=False)
    store_id = Column(Integer, ForeignKey("dim_store.id"), nullable=True)
    transaction_date = Column(DateTime)
    settlement_id = Column(String(50))
    transaction_type = Column(String(20))
    order_id = Column(String(50))
    sku = Column(String(50))
    description = Column(String(500))
    quantity = Column(Integer, default=0)
    marketplace = Column(String(20))
    fulfillment = Column(String(20))
    order_city = Column(String(100))
    order_state = Column(String(50))
    order_postal = Column(String(20))
    tax_collection_model = Column(String(50))
    product_sales = Column(Numeric(12, 2), default=0)
    product_sales_tax = Column(Numeric(12, 2), default=0)
    shipping_credits = Column(Numeric(12, 2), default=0)
    shipping_credits_tax = Column(Numeric(12, 2), default=0)
    gift_wrap_credits = Column(Numeric(12, 2), default=0)
    giftwrap_credits_tax = Column(Numeric(12, 2), default=0)
    regulatory_fee = Column(Numeric(12, 2), default=0)
    tax_on_regulatory_fee = Column(Numeric(12, 2), default=0)
    promotional_rebates = Column(Numeric(12, 2), default=0)
    promotional_rebates_tax = Column(Numeric(12, 2), default=0)
    marketplace_withheld_tax = Column(Numeric(12, 2), default=0)
    selling_fee = Column(Numeric(12, 2), default=0)
    fba_fee = Column(Numeric(12, 2), default=0)
    other_transaction_fee = Column(Numeric(12, 2), default=0)
    other_amount = Column(Numeric(12, 2), default=0)
    total = Column(Numeric(12, 2), default=0)
    transaction_status = Column(String(20))
    transaction_release_date = Column(DateTime)
    created_at = Column(TIMESTAMP, server_default=func.now())


class MonthlySummary(Base):
    __tablename__ = "monthly_summary"
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    country_id = Column(Integer, ForeignKey("dim_country.id"), nullable=False)
    store_id = Column(Integer, ForeignKey("dim_store.id"), nullable=True)
    product_id = Column(Integer, ForeignKey("dim_product.id"), nullable=False)
    time_id = Column(Integer, ForeignKey("dim_time.id"), nullable=False)
    product_sales_usd = Column(Numeric(12, 2), default=0)
    commission_usd = Column(Numeric(12, 2), default=0)
    fba_fee_usd = Column(Numeric(12, 2), default=0)
    amazon_payout_usd = Column(Numeric(12, 2), default=0)
    product_cost_rmb = Column(Numeric(12, 2), default=0)
    freight_cost_rmb = Column(Numeric(12, 2), default=0)
    ad_spend_usd = Column(Numeric(12, 2), default=0)
    storage_fee_usd = Column(Numeric(12, 2), default=0)
    returns_fee_usd = Column(Numeric(12, 2), default=0)
    inbound_fee_usd = Column(Numeric(12, 2), default=0)
    promo_rebate_usd = Column(Numeric(12, 2), default=0)
    promo_rebate_tax_usd = Column(Numeric(12, 2), default=0)
    marketplace_withheld_tax_usd = Column(Numeric(12, 2), default=0)
    adjustment_usd = Column(Numeric(12, 2), default=0)
    exchange_rate = Column(Numeric(10, 4), default=0)
    product_sales_rmb = Column(Numeric(12, 2), default=0)
    net_profit_rmb = Column(Numeric(12, 2), default=0)
    net_profit_rate = Column(Numeric(8, 4), default=0)
    order_count = Column(Integer, default=0)
    order_qty = Column(Integer, default=0)
    ad_sales_usd = Column(Numeric(12, 2), default=0)
    acos = Column(Numeric(8, 4), default=0)
    roas = Column(Numeric(8, 4), default=0)
    ctr = Column(Numeric(8, 4), default=0)
    cpc = Column(Numeric(8, 4), default=0)
    impressions = Column(Integer, default=0)
    clicks = Column(Integer, default=0)
    ad_orders = Column(Integer, default=0)
    conversion_rate = Column(Numeric(8, 4), default=0)


class RawAdvertising(Base):
    __tablename__ = "raw_advertising"
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    country_id = Column(Integer, ForeignKey("dim_country.id"), nullable=False)
    store_id = Column(Integer, ForeignKey("dim_store.id"), nullable=True)
    product_field = Column(String(200))
    asin = Column(String(50))
    status_val = Column(String(50))
    ad_type = Column(String(50))
    eligibility = Column(String(100))
    sales_usd = Column(Numeric(12, 2), default=0)
    roas = Column(Numeric(10, 4), default=0)
    conversion_rate = Column(Numeric(10, 4), default=0)
    impressions = Column(Integer, default=0)
    clicks = Column(Integer, default=0)
    ctr = Column(Numeric(10, 4), default=0)
    spend_usd = Column(Numeric(12, 2), default=0)
    cpc = Column(Numeric(10, 4), default=0)
    orders = Column(Integer, default=0)
    acos = Column(Numeric(10, 4), default=0)
    ntb_orders = Column(Integer, default=0)
    ntb_order_pct = Column(Numeric(10, 4), default=0)
    ntb_sales_usd = Column(Numeric(12, 2), default=0)
    new_to_brand_sales_pct = Column(Numeric(10, 4), default=0)
    visible_impressions = Column(Integer, default=0)
    raw_data = Column(JSON)
    created_at = Column(TIMESTAMP, server_default=func.now())


class RawStorageFee(Base):
    __tablename__ = "raw_storage_fee"
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    country_id = Column(Integer, ForeignKey("dim_country.id"), nullable=False)
    store_id = Column(Integer, ForeignKey("dim_store.id"), nullable=True)
    asin = Column(String(50))
    fnsku = Column(String(50))
    product_name = Column(String(500))
    fulfillment_center = Column(String(20))
    country_code = Column(String(50))
    longest_side = Column(Numeric(10, 4), default=0)
    median_side = Column(Numeric(10, 4), default=0)
    shortest_side = Column(Numeric(10, 4), default=0)
    measurement_units = Column(String(50))
    weight = Column(Numeric(10, 4), default=0)
    weight_units = Column(String(50))
    item_volume = Column(Numeric(12, 6), default=0)
    volume_units = Column(String(50))
    product_size_tier = Column(String(50))
    average_quantity_on_hand = Column(Numeric(10, 2), default=0)
    average_quantity_pending_removal = Column(Numeric(10, 2), default=0)
    estimated_total_item_volume = Column(Numeric(12, 6), default=0)
    month_of_charge = Column(String(20))
    storage_utilization_ratio = Column(Numeric(10, 2), default=0)
    storage_utilization_ratio_units = Column(String(50))
    base_rate = Column(Numeric(10, 4), default=0)
    utilization_surcharge_rate = Column(Numeric(10, 4), default=0)
    avg_qty_for_sus = Column(Numeric(10, 2), default=0)
    est_vol_for_sus = Column(Numeric(12, 6), default=0)
    est_base_msf = Column(Numeric(12, 4), default=0)
    est_sus = Column(Numeric(12, 4), default=0)
    currency = Column(String(10))
    estimated_monthly_storage_fee = Column(Numeric(12, 4), default=0)
    dangerous_goods_storage_type = Column(String(100))
    eligible_for_inventory_discount = Column(String(10))
    qualifies_for_inventory_discount = Column(String(10))
    total_incentive_fee_amount = Column(Numeric(12, 4), default=0)
    breakdown_incentive_fee_amount = Column(Numeric(12, 4), default=0)
    average_quantity_customer_orders = Column(Numeric(10, 2), default=0)
    raw_data = Column(JSON)
    created_at = Column(TIMESTAMP, server_default=func.now())


class RawReturns(Base):
    __tablename__ = "raw_returns"
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    country_id = Column(Integer, ForeignKey("dim_country.id"), nullable=False)
    store_id = Column(Integer, ForeignKey("dim_store.id"), nullable=True)
    asin = Column(String(50))
    asin_fee_category = Column(String(100))
    fnsku = Column(String(50))
    product_name = Column(String(500))
    longest_side = Column(Numeric(10, 4), default=0)
    median_side = Column(Numeric(10, 4), default=0)
    shortest_side = Column(Numeric(10, 4), default=0)
    measurement_units = Column(String(50))
    unit_weight = Column(Numeric(10, 4), default=0)
    dimensional_weight = Column(Numeric(10, 4), default=0)
    shipping_weight = Column(Numeric(10, 4), default=0)
    weight_units = Column(String(50))
    sku_sizetier = Column(String(50))
    month_of_shipment = Column(String(20))
    asin_shipped_units = Column(Integer, default=0)
    asin_return_threshold_percent = Column(Numeric(10, 4), default=0)
    asin_return_threshold_units = Column(Integer, default=0)
    asin_returned_units = Column(Integer, default=0)
    sku_returned_units_nsp_exempted = Column(Integer, default=0)
    sku_returned_units_charged = Column(Integer, default=0)
    sku_fee_per_unit = Column(Numeric(10, 4), default=0)
    sku_returns_fee = Column(Numeric(12, 4), default=0)
    month_of_charge = Column(String(20))
    currency = Column(String(10))
    raw_data = Column(JSON)
    created_at = Column(TIMESTAMP, server_default=func.now())


class RawInbound(Base):
    __tablename__ = "raw_inbound"
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    country_id = Column(Integer, ForeignKey("dim_country.id"), nullable=False)
    store_id = Column(Integer, ForeignKey("dim_store.id"), nullable=True)
    transaction_date = Column(DateTime)
    inbound_plan_id = Column(String(100))
    fba_shipment_id = Column(String(50))
    country_region = Column(String(50))
    fnsku = Column(String(50))
    asin = Column(String(50))
    planned_inbound_service = Column(String(100))
    planned_shipment_qty = Column(Integer, default=0)
    eligible_shipment_qty = Column(Integer, default=0)
    inbound_defect_type = Column(String(100))
    actual_fee_segment = Column(String(100))
    planned_inbound_region = Column(String(50))
    actual_inbound_region = Column(String(50))
    actual_received_qty = Column(Integer, default=0)
    product_size_segment = Column(String(50))
    shipping_weight = Column(Numeric(10, 4), default=0)
    weight_unit = Column(String(50))
    inbound_placement_fee_rate = Column(Numeric(10, 4), default=0)
    eligible_actual_incentive = Column(Numeric(12, 4), default=0)
    currency = Column(String(10))
    inbound_placement_fee_total = Column(Numeric(12, 4), default=0)
    total_fee = Column(Numeric(12, 4), default=0)
    raw_data = Column(JSON)
    created_at = Column(TIMESTAMP, server_default=func.now())


class RawLongTermStorage(Base):
    __tablename__ = "raw_long_term_storage"
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    country_id = Column(Integer, ForeignKey("dim_country.id"), nullable=False)
    store_id = Column(Integer, ForeignKey("dim_store.id"), nullable=True)
    snapshot_date = Column(String(30))
    sku = Column(String(100))
    fnsku = Column(String(50))
    asin = Column(String(50))
    product_name = Column(String(500))
    condition_val = Column(String(50))
    per_unit_volume = Column(Numeric(12, 6), default=0)
    currency = Column(String(10))
    volume_unit = Column(String(50))
    country = Column(String(50))
    qty_charged = Column(Integer, default=0)
    amount_charged = Column(Numeric(12, 4), default=0)
    surcharge_age_tier = Column(String(50))
    rate_surcharge = Column(Numeric(10, 4), default=0)
    raw_data = Column(JSON)
    created_at = Column(TIMESTAMP, server_default=func.now())
